import { Link } from "wouter";

interface PolicySection {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
}

const sections: PolicySection[] = [
  {
    title: "1. Introduction",
    paragraphs: [
      "This Privacy Policy describes how 9286721 CANADA INC. (hereinafter \"we\", \"our\", or \"Ha-Ha.ai\") collects, uses, stores, and protects your personal information when you use the Ha-Ha.ai mobile application and related services.",
      "By using Ha-Ha.ai, you agree to the practices described in this policy. If you do not agree with these practices, please do not use the application.",
    ],
  },
  {
    title: "2. Controller of Personal Information",
    paragraphs: [
      "The controller of your personal information is:",
      "9286721 CANADA INC.",
      "Email: info@ha-ha.ai",
      "Privacy Officer: Laurent Bernier",
    ],
  },
  {
    title: "3. Personal Information We Collect",
    paragraphs: ["3.1 Information you provide directly"],
    bullets: [
      "Email address and password when creating your account",
      "Apple ID (if you use Sign in with Apple)",
      "Username or nickname (optional)",
      "Profile preferences (language, app settings)",
      "Content of your conversations with AI characters in the application",
      "Images you share in chat (from your library or camera)",
    ],
  },
  {
    title: "3.2 Information collected automatically",
    bullets: [
      "Usage data: frequency of use, features used, and session duration",
      "Technical data: device type, operating system version, application version",
      "Subscription data: plan type, renewal dates, and payment history",
    ],
  },
  {
    title: "3.3 Voice data",
    paragraphs: [
      "When you use voice mode, your voice is captured through your device microphone and converted to text (speech recognition). These voice recordings are processed in real time and are not stored on our servers. Only the resulting text is used to generate a response.",
      "Voice responses generated by the application (speech synthesis) use cloned voices from artists who have provided explicit consent. No user biometric data is collected, stored, or analyzed.",
    ],
  },
  {
    title: "4. Purposes of Collection and Use",
    paragraphs: ["We use your personal information for the following purposes:"],
    bullets: [
      "Provide, maintain, and improve application features",
      "Generate personalized conversational responses with AI characters",
      "Manage your account, subscription, and access to premium features",
      "Synchronize your conversations across your devices",
      "Apply usage quotas associated with your plan",
      "Ensure application security and prevent abuse",
      "Comply with legal obligations",
    ],
  },
  {
    title: "5. Sharing with Third Parties",
    paragraphs: [
      "We do not sell your personal information. We share certain data with the following service providers strictly to operate the application:",
      "5.1 Service providers",
    ],
    bullets: [
      "Supabase (authentication, data storage, synchronization) — hosted in the United States",
      "Anthropic (AI text generation) — hosted in the United States",
      "ElevenLabs (speech synthesis) — hosted in the United States",
      "Stripe (payment processing) — hosted in the United States",
      "RevenueCat (in-app subscription management) — hosted in the United States",
      "Apple (in-app purchases and Sign in with Apple) — hosted in the United States",
    ],
  },
  {
    title: "5.2 Transfers outside Quebec",
    paragraphs: [
      "Some of our service providers are located in the United States. By using Ha-Ha.ai, you consent to the transfer of your personal information outside Quebec, in accordance with the requirements of Quebec Law 25. We ensure that these providers offer an adequate level of protection for your information.",
    ],
  },
  {
    title: "6. Data Retention",
    bullets: [
      "Account data: retained while your account is active. Deleted within 30 days after account deletion.",
      "Conversations: retained while your account is active, unless you manually delete them.",
      "Voice data (recordings): not retained. Processed in real time and immediately deleted.",
      "Payment data: retained in accordance with applicable tax and legal obligations.",
      "Usage data: retained in aggregated and anonymized form after 12 months.",
    ],
  },
  {
    title: "7. Your Rights",
    paragraphs: [
      "Under the Act Respecting the Protection of Personal Information in the Private Sector (Quebec Law 25), you have the following rights:",
    ],
    bullets: [
      "Right of access: obtain a copy of the personal information we hold about you.",
      "Right to rectification: request correction of inaccurate or incomplete information.",
      "Right to deletion: request deletion of your personal information, subject to legal obligations.",
      "Right to portability: obtain your information in a structured, commonly used format.",
      "Right to withdraw consent: you may withdraw your consent at any time. Withdrawal does not affect the lawfulness of processing performed before withdrawal.",
      "Right to de-indexation: request that your information stop being disseminated when legal conditions are met.",
    ],
  },
  {
    title: "Exercising your rights",
    paragraphs: [
      "To exercise your rights, contact us at info@ha-ha.ai. We will respond within 30 days.",
    ],
  },
  {
    title: "8. Security",
    paragraphs: [
      "We implement reasonable security measures to protect your personal information, including:",
    ],
    bullets: [
      "Encryption of data in transit (TLS/HTTPS)",
      "Secure authentication using JWT tokens",
      "Secure storage of authentication tokens on device",
      "Rate limiting on API access points",
      "Server-side data validation",
    ],
  },
  {
    title: "Privacy incidents",
    paragraphs: [
      "No system is infallible. In the event of a privacy incident, we will notify you as soon as possible, in accordance with Law 25.",
    ],
  },
  {
    title: "9. Minors",
    paragraphs: [
      "Ha-Ha.ai is not intended for persons under 13 years old. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us so we can take appropriate measures.",
      "For users aged 13 to 17, parental authority holder consent is required in accordance with Law 25.",
    ],
  },
  {
    title: "10. Tracking Technologies",
    paragraphs: [
      "The Ha-Ha.ai mobile application does not use web browser cookies. We use local storage on your device to maintain your session and preferences. This storage is strictly necessary for the application to function.",
    ],
  },
  {
    title: "11. Changes to this Policy",
    paragraphs: [
      "We may update this policy from time to time. In the event of a material change, we will notify you through the application or by email. The latest update date appears at the top of this document.",
      "Your continued use of the application after a change constitutes your acceptance of the updated policy.",
    ],
  },
  {
    title: "12. Contact Us",
    paragraphs: [
      "For any questions regarding this privacy policy, your personal information, or to exercise your rights, please contact us:",
      "9286721 CANADA INC.",
      "Email: info@ha-ha.ai",
      "Privacy Officer: Laurent Bernier",
      "If you are not satisfied with our response, you may file a complaint with the Quebec Access to Information Commission (CAI): www.cai.gouv.qc.ca",
    ],
  },
];

export default function PrivacyPolicyPageEn() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <main className="mx-auto w-full max-w-4xl px-4 pb-20 pt-10 sm:px-6 lg:px-8">
        <div className="mb-8">
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            ← Back to home
          </Link>
        </div>

        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-lg text-muted-foreground">Ha-Ha.ai</p>
        <p className="mt-1 text-sm text-muted-foreground">Last updated: 2026-04-13</p>

        <div className="mt-10 space-y-8">
          {sections.map((section) => (
            <section key={section.title} className="space-y-3">
              <h2 className="text-xl font-semibold">{section.title}</h2>
              {section.paragraphs?.map((paragraph) => (
                <p key={paragraph} className="leading-7 text-foreground/90">
                  {paragraph}
                </p>
              ))}
              {section.bullets && (
                <ul className="list-disc space-y-2 pl-6 text-foreground/90">
                  {section.bullets.map((bullet) => (
                    <li key={bullet} className="leading-7">
                      {bullet}
                    </li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
